import type { NextPage } from 'next'
import Head from 'next/head'
import { A } from '../styles'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to FE Workshop
        </h1>
        <A href='/form_a'>Form A</A>
        <A href='/form_b'>Form B</A>
      </main>
      <footer className={styles.footer}>
        Workshop
      </footer>
    </div>
  )
}

export default Home
